version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevents overwriting node_modules
    ports:
      - "5002:5000"
    command: npx ts-node-dev --respawn --transpile-only src/index.ts
    

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
